defmodule MAVLink.Router do
  @moduledoc """
  Connect to serial, udp and tcp ports and listen for, validate and
  forward MAVLink messages towards their destinations on other connections
  and/or Elixir processes subscribing to messages.

  The rules for MAVLink packet forwarding are described here:

    https://mavlink.io/en/guide/routing.html

  and here:

    http://ardupilot.org/dev/docs/mavlink-routing-in-ardupilot.html
  """

  use GenServer
  require Logger

  import MAVLink.Utils, only: [parse_ip_address: 1, parse_positive_integer: 1]
  import Enum, only: [map: 2]

  alias MAVLink.Types
  alias MAVLink.Message
  alias MAVLink.Router
  alias MAVLink.LocalConnection
  alias MAVLink.RouteTable
  alias MAVLink.Forwarder
  alias MAVLink.SerialConnection
  alias MAVLink.TCPOutConnection
  alias MAVLink.UDPInConnection
  alias MAVLink.UDPOutConnection
  alias Circuits.UART

  @typedoc """
  Represents the state of the MAVLink.Router. Initial values should be set in config.exs.

  ## Fields
  - dialect:            The MAVLink dialect module generated by mix mavlink from a MAVLink definition file
  - connection_strings: Configuration strings describing the network and serial connections MAVLink messages
                        are to be received and sent over. Allowed formats are:

                        ```udpin:<local ip>:<local port>
                        udpout:<remote ip>:<remote port>
                        tcpout:<remote ip>:<remote port>
                        serial:<device>:<baud rate>```

                        Note there is no tcpin connection - tcp is rarely used for MAVLink, the exception
                        being SITL testing which requires a tcpout connection.

  - connections:        A map containing the state of the connections described by connection_strings.
                        The map is keyed by the port, device or socket to allow the corresponding connection
                        state to be easily retrieved when we receive or forward a message.
  """
  defstruct [
    dialect: nil,
    connection_strings: [],
    connections: %{}
  ]

  @type mavlink_address :: Types.mavlink_address
  @type mavlink_connection :: Types.connection
  @type t :: %Router{
               dialect: module | nil,
               connection_strings: [String.t()],
               connections: %{}
             }

  ##############
  # Router API #
  ##############

  @doc """
  Start the MAVLink Router service. You should not call this directly, use the MAVLink application
  to start this under a supervision tree with the services it expects to use.

  ## Parameters
  - dialect:            Name of the module generated by mix mavlink task to represent the enumerations
                        and messages of a particular MAVLink dialect
  - system:             The System id of this system  1..255, typically low for vehicles and high for
                        ground stations
  - component:          The component id of this system 1..255, typically 1 for the autopilot
  - connection_strings: A list of strings in the following formats:

                        udpin:<local ip>:<local port>
                        udpout:<remote ip>:<remote port>
                        tcpout:<remote ip>:<remote port>
                        serial:<device>:<baud rate>

  - opts:               Standard GenServer options
  """
  @spec start_link(
          %{system: 1..255, component: 1..255, dialect: module, connection_strings: [String.t()]},
          [{atom, any}]
        ) :: {:ok, pid}
  def start_link(args, opts \\ []) do
    GenServer.start_link(
      __MODULE__,
      args,
      [{:name, __MODULE__} | opts]
    )
  end

  @doc """
  Subscribes the calling process to MAVLink messages from the installed dialect matching the query.

  ## Parameters

  - query:  Keyword list of zero or more of the following query keywords:

    message:          message_module | :unknown (use latter with as_frame)
    source_system:    integer 0..255
    source_component: integer 0..255
    target_system:    integer 0..255
    target_component: integer 0..255
    as_frame:         true|false (default false, shows entire message frame with sender/target details)

  ## Example

  ```
    MAVLink.Router.subscribe message: MAVLink.Message.Heartbeat, source_system: 1
  ```
  """
  @type subscribe_query_id_key :: :source_system | :source_component | :target_system | :target_component
  @spec subscribe([{:message, Message.t} | {subscribe_query_id_key, 0..255} | {:as_frame, boolean}]) ::
          :ok | {:error, :invalid_message}
  def subscribe(query \\ []) do
    with message <- Keyword.get(query, :message),
         true <- message == nil or Code.ensure_loaded?(message) do
      query =
        [
          message: nil,
          source_system: 0,
          source_component: 0,
          target_system: 0,
          target_component: 0,
          as_frame: false
        ]
        |> Keyword.merge(query)
        |> Enum.into(%{})

      RouteTable.subscribe(query, self())
    else
      false -> {:error, :invalid_message}
    end
  end

  @doc """
  Un-subscribes calling process from all existing subscriptions

  ## Example

  ```
    MAVLink.Router.unsubscribe
  ```
  """
  @spec unsubscribe() :: :ok
  def unsubscribe(), do: RouteTable.unsubscribe(self())

  @doc """
  Send a MAVLink message to one or more recipients using available
  connections. For now if destination is unreachable it will log
  a warning

  ## Parameters

  - message: A MAVLink message structure from the installed dialect
  - version: Force sending using a specific MAVLink protocol (default 2)

  ## Example

  ```
    MAVLink.Router.pack_and_send(
      %APM.RcChannelsOverride{
        target_system: 1,
        target_component: 1,
        chan1_raw: 1500,
        chan2_raw: 1500,
        chan3_raw: 1500,
        chan4_raw: 1500,
        chan5_raw: 1500,
        chan6_raw: 1500,
        chan7_raw: 1500,
        chan8_raw: 1500,
        chan9_raw: 0,
        chan10_raw: 0,
        chan11_raw: 0,
        chan12_raw: 0,
        chan13_raw: 0,
        chan14_raw: 0,
        chan15_raw: 0,
        chan16_raw: 0,
        chan17_raw: 0,
        chan18_raw: 0
      }
    )
  ```
  """
  def pack_and_send(message, version \\ 2) do
    LocalConnection.pack_and_send(message, version)
  end

  #######################
  # GenServer Callbacks #
  #######################

  @impl true
  def init(%{dialect: nil}) do
    {:error, :no_mavlink_dialect_set}
  end

  def init(args) do
    _ = map(args.connection_strings, &connect/1)
    {:ok, %Router{dialect: args.dialect, connection_strings: args.connection_strings}}
  end

  @impl true
  def handle_info(message = {:udp, socket, address, port, _},
                  state = %Router{connections: connections, dialect: dialect}) do
    {
      :noreply,
      case connections[{socket, address, port}] do
        connection = %UDPInConnection{} ->
          UDPInConnection.handle_info(message, connection, dialect)

        connection = %UDPOutConnection{} ->
          UDPOutConnection.handle_info(message, connection, dialect)

        nil ->
          UDPInConnection.handle_info(message, nil, dialect)
      end
      |> process_incoming(state)
    }
  end

  def handle_info(message = {:tcp, socket, _}, state) do
    {
      :noreply,
      TCPOutConnection.handle_info(message, state.connections[socket], state.dialect)
      |> process_incoming(state)
    }
  end

  def handle_info({:tcp_closed, socket}, state) do
    %TCPOutConnection{address: address, port: port} = state.connections[socket]
    spawn(TCPOutConnection, :connect, [["tcpout", address, port], self()])
    {:noreply, remove_connection(socket, state)}
  end

  def handle_info(message = {:circuits_uart, port, raw}, state) when is_binary(raw) do
    {
      :noreply,
      SerialConnection.handle_info(message, state.connections[port], state.dialect)
      |> process_incoming(state)
    }
  end

  def handle_info({:circuits_uart, port, {:error, _reason}}, state) do
    %SerialConnection{baud: baud, uart: uart} = state.connections[port]
    spawn(SerialConnection, :connect, [["serial", port, baud, :poolboy.checkout(MAVLink.UARTPool)], self()])
    :ok = UART.close(uart)
    :poolboy.checkin(MAVLink.UARTPool, uart)
    {:noreply, remove_connection(port, state)}
  end

  def handle_info({:mavlink_forward, frame, connection_key}, state = %Router{connections: connections}) do
    case connections[connection_key] do
      nil ->
        {:noreply, state}

      connection ->
        forward(connection, frame)
        {:noreply, state}
    end
  end

  def handle_info({:add_connection, connection_key, connection},
                  state = %Router{connections: connections}) do
    RouteTable.register_wire(self(), connection_key)

    {
      :noreply,
      struct(state, connections: Map.put(connections, connection_key, connection))
    }
  end

  def handle_info(_msg, state) do
    {:noreply, state}
  end

  ####################
  # Helper Functions #
  ####################

  defp connect(connection_string) when is_binary(connection_string),
    do: connect(String.split(connection_string, [":", ","]))

  defp connect(tokens = ["udpin" | _]),
    do: spawn(UDPInConnection, :connect, [validate_address_and_port(tokens), self()])

  defp connect(tokens = ["udpout" | _]),
    do: spawn(UDPOutConnection, :connect, [validate_address_and_port(tokens), self()])

  defp connect(tokens = ["tcpout" | _]),
    do: spawn(TCPOutConnection, :connect, [validate_address_and_port(tokens), self()])

  defp connect(tokens = ["serial" | _]),
    do: spawn(SerialConnection, :connect, [validate_port_and_baud(tokens), self()])

  defp connect([invalid_protocol | _]),
    do: raise(ArgumentError, message: "invalid protocol #{invalid_protocol}")

  defp validate_address_and_port([protocol, address, port]) do
    case {parse_ip_address(address), parse_positive_integer(port)} do
      {{:error, :invalid_ip_address}, _} ->
        raise ArgumentError, message: "invalid ip address #{address}"

      {_, :error} ->
        raise ArgumentError, message: "invalid port #{port}"

      {parsed_address, parsed_port} ->
        [protocol, parsed_address, parsed_port]
    end
  end

  defp validate_port_and_baud(["serial", port, baud]) do
    case {is_binary(port), parse_positive_integer(baud)} do
      {false, _} ->
        raise ArgumentError, message: "Invalid port #{port}"

      {_, :error} ->
        raise ArgumentError, message: "invalid baud rate #{baud}"

      {true, parsed_baud} ->
        ["serial", port, parsed_baud, :poolboy.checkout(MAVLink.UARTPool)]
    end
  end

  defp remove_connection(connection_key, state = %Router{connections: connections}) do
    struct(state, connections: Map.delete(connections, connection_key))
  end

  defp process_incoming(
         {:ok, source_connection_key, source_connection, frame},
         state = %Router{connections: connections}
       ) do
    state = struct(state, connections: Map.put(connections, source_connection_key, source_connection))
    :ok = Forwarder.route(self(), source_connection_key, frame)
    state
  end

  defp process_incoming(
         {:error, _reason, connection_key, connection},
         state = %Router{connections: connections}
       ) do
    struct(state, connections: Map.put(connections, connection_key, connection))
  end

  defp forward(connection = %UDPInConnection{}, frame), do: UDPInConnection.forward(connection, frame)
  defp forward(connection = %UDPOutConnection{}, frame), do: UDPOutConnection.forward(connection, frame)
  defp forward(connection = %TCPOutConnection{}, frame), do: TCPOutConnection.forward(connection, frame)
  defp forward(connection = %SerialConnection{}, frame), do: SerialConnection.forward(connection, frame)
  defp forward(connection = %LocalConnection{}, frame), do: LocalConnection.forward(connection, frame)
end
